let str = "         Hello World\n jack\n    ";
console.log(str.anchor()); // returns anchor html tag
console.log(str.big()); // returns <big> element
console.log(str.blink()); // returns <blink> element
console.log(str.bold()); // returns <b> element
console.log(str.charAt(6)); // returns character on given position in string
console.log(str.charCodeAt(6)); // returns ascii of character on given position in string
console.log(str.codePointAt(6)); // returns ascii of character on given position in string(UTF-16)
console.log(str.concat("Junaid")); // returns concatinated string
console.log(str); // original string will not change
console.log(str.endsWith("ld")); // checks if string ends with given sequence or not (boolean)
console.log(str.fixed()); // returns <tt> html element
console.log(str.fontcolor("red")); // returns <font color='red'> element
console.log(str.fontsize(14)); // returns <font size="14"> element
console.log(str.includes("junaid")); // checks if given sequence is in string or not
console.log(str.indexOf("l", 4)); // returns the first index of given sequence in string, seconds argument is starting index(comparision starts from this index)
console.log(str.italics()); // returns <i>string</i> html tag
console.log(str.lastIndexOf("l", 8)); // returns the last index of given sequence in string, seconds argument is starting index from last(comparision ends on this index)
console.log(str.link("www.google.com")); // return <a href="url">String</a> tag
console.log(str.match(/l/)); // matches string with given regex and returns array [matched first string, index, input, groups]
console.log(JSON.stringify(str.matchAll(/d/g))); // matches string with given regex, returns object of all matched array [matched string, index, input, groups]
console.log(str.padEnd(20, "Jack")); //this will add the given string in end to original string multiple times until it reaches given length
console.log(str.padStart(20, "Jack")); //this will add the given string instart to original string multiple times until it reaches given length
console.log(str.repeat(12)); //this will same string to given times in input
console.log(str.replace("l", "z")); //this replaces given seq's first occurance with new seq in the string
console.log(str.replaceAll("l", "z")); //this replaces given seq's all occurances with new seq in the string
console.log(str.search("or")); //this replaces given seq's all occurances with new seq in the string
console.log(str.slice(4, 8)); //this returns substring between start and end indexes of original string
console.log(str.small()); //this returns <small>string</small> html tag
console.log(str.split("l")); //this returns array of substrings generated by spilitting original string on the basis of given splitter
console.log(str.startsWith("h")); //this checks if stings starts with given seq or not
console.log(str.strike()); //this returns <strike>string</strike> tag
console.log(str.sub()); //this returns <sub>string</sub> tag
console.log(str.substr(2, 10)); //this returns substring from given starting index and of given length
console.log(str.substring(2, 10)); //this returns substring from given starting index and and till given ending index
console.log(str.sup()); //this returns <sup>string</sup>
console.log(str.toLocaleLowerCase("en-US")); //this returns lower case string (with locale support)
console.log(str.toLowerCase()); //this returns lower case string (without locale support)
console.log(str.toLocaleUpperCase('en-US')); //this returns upper case string (with locale support)
console.log(str.toUpperCase()); //this returns upper case string (without locale support)
console.log(str.trim()); //this returns string after removing leading and trailing white spaces and line termanating(new line chars)
console.log(str.trimEnd()); //this returns string after removing trailing white spaces and line termanating(new line chars)
console.log(str.trimLeft()); //this returns string after removing leading white spaces and line termanating(new line chars)
console.log(str.trimRight()); //this returns string after removing trailing white spaces and line termanating(new line chars)
console.log(str.trimStart()); //this returns string after removing leading white spaces and line termanating(new line chars)
console.log("=-=======================-=");
console.log(str.valueOf()); //this returns primitive value of string